spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#      add-mappings: false
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
logging:
  file: /log/xj-book-home.log

server:
  port: 8001
  use-forward-headers: true