spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  use-forward-headers: true
  port: 8000