spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate.order_by.default_null_ordering: last
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test